{\rtf1\ansi\ansicpg1252\cocoartf2513
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
language: objective-c\
\
osx_image: xcode10.1\
env:\
  matrix:\
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'\
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'\
\
script:\
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project AsangaSwiftyLib.xcodeproj -scheme AsangaSwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES}